# Generated by Django 5.2.6 on 2026-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0014_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumgroup',
            name='group_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
