# Generated by Django 5.2.6 on 2026-03-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0015_alter_premiumgroup_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='turnir_teams_count',
            field=models.IntegerField(default=2),
        ),
    ]
