# Generated by Django 5.2.6 on 2026-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0016_gamesettings_turnir_teams_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team_count',
            field=models.IntegerField(default=2),
        ),
    ]
