# Generated by Django 5.2.6 on 2026-04-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0017_game_team_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricestones',
            name='money_in_money',
            field=models.TextField(blank=True, default="77 Рубль | 10 000 UZS - <tg-emoji emoji-id='5472030678633684592'>💶</tg-emoji> 13 000\n385 Рубль | 50 000 UZS - <tg-emoji emoji-id='5472030678633684592'>💶</tg-emoji> 65 000\n770 Рубль | 100 000 UZS - <tg-emoji emoji-id='5472030678633684592'>💶</tg-emoji> 130 000\n3850 Рубль | 500 000 UZS - <tg-emoji emoji-id='5472030678633684592'>💶</tg-emoji> 650 000\n7700 Рубль | 1 000 000 UZS - <tg-emoji emoji-id='5472030678633684592'>💶</tg-emoji> 1 300 000"),
        ),
        migrations.AlterField(
            model_name='pricestones',
            name='stone_in_money',
            field=models.TextField(blank=True, default="77 Рубль | 10 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>10\n208 Рубль | 27 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>30\n323 Рубль | 42 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>50\n431 Рубль | 56 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>70\n577 Рубль | 75 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>100\n1154 Рубль | 150 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>200\n1731 Рубль | 225 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>300\n2770 Рубль | 360 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>500\n5834 Рубль | 700 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>1000\n10154 Рубль | 1 320 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>2000\n14308 Рубль | 1 860 000 UZS - <tg-emoji emoji-id='5471952986970267163'>💎</tg-emoji>3000"),
        ),
    ]
